### ISSUE TITLE
After the las update, the app crashes.

### ISSUE THREAD

**Issue by mCr86** [melianmiko/OpenFreebuds#39]
It crashes just after the FreeBuds's connection.

```
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/openfreebuds_qt/utils/qt_utils.py", line 33, in qt_error_handler
    yield
  File "/usr/lib/python3.12/site-packages/openfreebuds_qt/tray/main.py", line 136, in _update_loop
    await self._update_ui(event)
  File "/usr/lib/python3.12/site-packages/openfreebuds_qt/tray/main.py", line 96, in _update_ui
    await self.menu.on_core_event(event, state)
  File "/usr/lib/python3.12/site-packages/openfreebuds_qt/tray/menu.py", line 127, in on_core_event
    await self.equalizer_submenu.update_ui()
  File "/usr/lib/python3.12/site-packages/openfreebuds_qt/tray/menu_equalizer.py", line 25, in update_ui
    for code in options.split(","):
                ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
```
Attached the full bug report.
[OpenFreebuds_report.log](https://github.com/user-attachments/files/17228321/OpenFreebuds_report.log)

**Comment by melianmiko** [comment]
Version v0.14.1 released, bug should be fixed in that release.
