### ISSUE TITLE
OpenFreeBuds crashes on device switch with "Switch automatically" enabled

### ISSUE THREAD

**Issue by S-trace** [melianmiko/OpenFreebuds#8]
Hi!

I have two FreeBuds 4i pairs, and OpenFreeBuds crashes when I disconnect one pair and connect other pair:
```
$ openfreebuds
INFO:Applet:Thread-3 (_thread)  Change icon: state_no_dev
DEBUG:Applet:Thread-3 (_thread)  Menu updated, hash=8629732df04f6498e397e174d3d3e7abaea67a2b
INFO:AutoConfig:Thread-3 (_thread)  Attempt to change device automatically
INFO:AutoConfig:Thread-3 (_thread)  Use HUAWEI FreeBuds 4i DE:AD:BE:EF:11:11
DEBUG:FreebudsManager:Thread-3 (_thread)  Running mainloop via safe wrapper
DEBUG:FreebudsManager:Thread-5 (_thread)  Started
INFO:FreebudsManager:Thread-5 (_thread)  Trying to create SPP device and connect...
INFO:FreebudsManager:Thread-5 (_thread)  State changed to 3
INFO:Applet:Thread-3 (_thread)  Change icon: state_wait
DEBUG:Applet:Thread-3 (_thread)  Menu updated, hash=e568c52631f493e51ad78addf721573a51f66b0d
INFO:SPPDevice:Thread-5 (_thread)  Found serial port DE:AD:BE:EF:11:11:16 from UUID
DEBUG:SPPDevice:Thread-5 (_thread)  Starting via safe wrapper
INFO:SPPDevice:Thread-6 (_thread)  starting recv...
DEBUG:SPPDevice:Thread-5 (_thread)  Starting via safe wrapper
INFO:SPPDevice:Thread-7 (_thread)  starting send thread...
DEBUG:SPPDevice:Thread-7 (_thread)  send 5a001f0001070100020003000400050006000700080009000a000b000c000f00190002d9
DEBUG:SPPDevice:Thread-6 (_thread)  recv 010702020124030b484c314f54454d325f56420709312e392e302e3139380910553355424232314332383130343335360a0f42544654303030312d3030303132340f0842544654303030311810424239444b4432314255413137393634190105db
DEBUG:SPPDevice:Thread-7 (_thread)  send 5a0007000c0201000300d9d2
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0c02030b7a682d434e2c656e2d4742040101ee
DEBUG:SPPDevice:Thread-7 (_thread)  send 5a0009000108010002000300fbb9
DEBUG:SPPDevice:Thread-6 (_thread)  recv 01080101640203646464030300000040
DEBUG:SPPDevice:Thread-7 (_thread)  send 5a0005002b2a0100427e
DEBUG:SPPDevice:Thread-6 (_thread)  recv 2b2a0102000015
DEBUG:SPPDevice:Thread-7 (_thread)  send 5a0005002b110100772a
DEBUG:SPPDevice:Thread-6 (_thread)  recv 2b11010100cf
DEBUG:SPPDevice:Thread-7 (_thread)  send 5a000500012d0101882a
DEBUG:SPPDevice:Thread-6 (_thread)  recv 012d010101f2
DEBUG:SPPDevice:Thread-7 (_thread)  send 5a000700012001000200e897
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0120010102020101030501020700ff33
DEBUG:SPPDevice:Thread-7 (_thread)  send 5a0007002b170100020030a7
DEBUG:SPPDevice:Thread-6 (_thread)  recv 2b1701010a02010a030b000102030405060708090aa4
DEBUG:SPPDevice:Thread-7 (_thread)  send 5a0007002b1901000200ff0f
DEBUG:SPPDevice:Thread-6 (_thread)  recv 2b19010101020101030a0102030405060708090a5a
INFO:FreebudsManager:Thread-5 (_thread)  State changed to 4
INFO:Applet:Thread-3 (_thread)  Change icon: connected_0_100
DEBUG:Applet:Thread-3 (_thread)  Menu updated, hash=10537b1182a1f2a872af61a09eb92c4012ba2721
DEBUG:mmk-update:Thread-2 (_process)  latest release: 0.11
DEBUG:mmk-update:Thread-2 (_process)  update ui shouldn't be shown
DEBUG:TkinterTools:Thread-8 (th)  Starting UI thread...
WARNING:FreebudsLocale:Thread-8 (th)  missing in base i18n: first_run_message
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000127047b7b2254797065223a2242544654303030312d3030303132347c307865627c30783638222c2254696d65223a307836336166646639312c224944223a3078352c22564944223a307831353562646439662c22566572223a22312e392e302e313938222c22436f6465223a3078362c22537562436f6465223a3078307dc5
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000127047b7b2254797065223a2242544654303030312d3030303132347c307831637c30783737222c2254696d65223a307836336166646639302c224944223a3078342c22564944223a307831386461613261362c22566572223a22312e392e302e313938222c22436f6465223a3078352c22537562436f6465223a3078307db3
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000107047b7b2254797065223a2242544654303030312d3030303132347c307865657c30783639222c2254696d65223a307836336166646661622c224944223a3078352c22564944223a307831353562646439662c22566572223a22312e392e302e313938222c22436f6465223a3078312c22537562436f6465223a3078317d3b
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000127047b7b2254797065223a2242544654303030312d3030303132347c307831647c30783738222c2254696d65223a307836336166646639332c224944223a3078342c22564944223a307831386461613261362c22566572223a22312e392e302e313938222c22436f6465223a3078362c22537562436f6465223a3078307d96
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000012045f7b2254797065223a2242544654303030312d3030303132347c307866307c30783661222c2254696d65223a307836336166646661622c224944223a3078352c224f7574223a3078312c2254494d45444946464552454e4345223a307864647de4
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d01010302040000012204587b2254797065223a2242544654303030312d3030303132347c307832307c30783739222c2254696d65223a307836336166646662322c224944223a3078342c22436f6465223a3078362c22537562436f6465223a3078317da9
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000107047b7b2254797065223a2242544654303030312d3030303132347c307866317c30783662222c2254696d65223a307836336166646661632c224944223a3078352c22564944223a307831353562646439662c22566572223a22312e392e302e313938222c22436f6465223a3078312c22537562436f6465223a3078327d95
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000120047b7b2254797065223a2242544654303030312d3030303132347c307832317c30783761222c2254696d65223a307836336166646662322c224944223a3078342c22564944223a307831386461613261362c22566572223a22312e392e302e313938222c22436f6465223a3078342c22537562436f6465223a3078307d5d
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000108047b7b2254797065223a2242544654303030312d3030303132347c307866337c30783663222c2254696d65223a307836336166646661632c224944223a3078352c22564944223a307831353562646439662c22566572223a22312e392e302e313938222c22436f6465223a3078312c22537562436f6465223a3078367d7e
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000120047b7b2254797065223a2242544654303030312d3030303132347c307866367c30783664222c2254696d65223a307836336166646662312c224944223a3078352c22564944223a307831353562646439662c22566572223a22312e392e302e313938222c22436f6465223a3078342c22537562436f6465223a3078307d85
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d01010302040000012204587b2254797065223a2242544654303030312d3030303132347c307866377c30783665222c2254696d65223a307836336166646662312c224944223a3078352c22436f6465223a3078362c22537562436f6465223a3078317d37
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000120047b7b2254797065223a2242544654303030312d3030303132347c307866387c30783666222c2254696d65223a307836336166646662312c224944223a3078352c22564944223a307831353562646439662c22566572223a22312e392e302e313938222c22436f6465223a3078342c22537562436f6465223a3078307d9c
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000c0404587b2254797065223a2242544654303030312d3030303132347c307832617c30783762222c2254696d65223a307836336166646662322c224944223a3078342c22436f6465223a3078312c22537562436f6465223a3078307d86
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000c0404587b2254797065223a2242544654303030312d3030303132347c307866647c30783730222c2254696d65223a307836336166646662312c224944223a3078352c22436f6465223a3078312c22537562436f6465223a3078307dd8
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000120047b7b2254797065223a2242544654303030312d3030303132347c307832647c30783763222c2254696d65223a307836336166646662322c224944223a3078342c22564944223a307831386461613261362c22566572223a22312e392e302e313938222c22436f6465223a3078332c22537562436f6465223a3078317de1
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000120047b7b2254797065223a2242544654303030312d3030303132347c307832657c30783764222c2254696d65223a307836336166646662322c224944223a3078342c22564944223a307831386461613261362c22566572223a22312e392e302e313938222c22436f6465223a3078312c22537562436f6465223a3078317d59
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d01010302040000012204577b2254797065223a2242544654303030312d3030303132347c3078307c30783731222c2254696d65223a307836336166646662312c224944223a3078352c22436f6465223a3078352c22537562436f6465223a3078307d48
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d01010302040000012204587b2254797065223a2242544654303030312d3030303132347c307832667c30783765222c2254696d65223a307836336166646662322c224944223a3078342c22436f6465223a3078372c22537562436f6465223a3078317dbb
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000120047a7b2254797065223a2242544654303030312d3030303132347c3078317c30783732222c2254696d65223a307836336166646662322c224944223a3078352c22564944223a307831353562646439662c22566572223a22312e392e302e313938222c22436f6465223a3078332c22537562436f6465223a3078317d96
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000120047a7b2254797065223a2242544654303030312d3030303132347c3078327c30783733222c2254696d65223a307836336166646662322c224944223a3078352c22564944223a307831353562646439662c22566572223a22312e392e302e313938222c22436f6465223a3078312c22537562436f6465223a3078317d13
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d01010302040000012204577b2254797065223a2242544654303030312d3030303132347c3078337c30783734222c2254696d65223a307836336166646662322c224944223a3078352c22436f6465223a3078372c22537562436f6465223a3078317d2c
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d01010302040000012204587b2254797065223a2242544654303030312d3030303132347c307833367c30783766222c2254696d65223a307836336166646662322c224944223a3078342c22436f6465223a3078352c22537562436f6465223a3078307ded
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000123047a7b2254797065223a2242544654303030312d3030303132347c3078377c30783735222c2254696d65223a307836336166646662332c224944223a3078352c22564944223a307831353562646439662c22566572223a22312e392e302e313938222c22436f6465223a3078332c22537562436f6465223a3078307d6a
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000124047a7b2254797065223a2242544654303030312d3030303132347c3078397c30783736222c2254696d65223a307836336166646662332c224944223a3078352c22564944223a307831353562646439662c22566572223a22312e392e302e313938222c22436f6465223a3078312c22537562436f6465223a3078667d5a
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000124047a7b2254797065223a2242544654303030312d3030303132347c3078617c30783737222c2254696d65223a307836336166646662332c224944223a3078352c22564944223a307831353562646439662c22566572223a22312e392e302e313938222c22436f6465223a3078322c22537562436f6465223a3078617d10
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000124047b7b2254797065223a2242544654303030312d3030303132347c307833637c30783830222c2254696d65223a307836336166646662332c224944223a3078342c22564944223a307831386461613261362c22566572223a22312e392e302e313938222c22436f6465223a3078312c22537562436f6465223a3078667d18
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000123047b7b2254797065223a2242544654303030312d3030303132347c307833647c30783831222c2254696d65223a307836336166646662332c224944223a3078342c22564944223a307831386461613261362c22566572223a22312e392e302e313938222c22436f6465223a3078342c22537562436f6465223a3078307dc1
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d01010302040000012204587b2254797065223a2242544654303030312d3030303132347c307831307c30783738222c2254696d65223a307836336166653132632c224944223a3078352c22436f6465223a3078362c22537562436f6465223a3078317dcf
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000a0404587b2254797065223a2242544654303030312d3030303132347c307833657c30783832222c2254696d65223a307836336166646662332c224944223a3078342c22436f6465223a3078302c22537562436f6465223a3078307d25
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000a0404587b2254797065223a2242544654303030312d3030303132347c307833667c30783833222c2254696d65223a307836336166646662332c224944223a3078342c22436f6465223a3078302c22537562436f6465223a3078307ddd
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000120047b7b2254797065223a2242544654303030312d3030303132347c307831317c30783739222c2254696d65223a307836336166653132632c224944223a3078352c22564944223a307831353562646439662c22566572223a22312e392e302e313938222c22436f6465223a3078342c22537562436f6465223a3078307dd4
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000124047b7b2254797065223a2242544654303030312d3030303132347c307834307c30783834222c2254696d65223a307836336166646662332c224944223a3078342c22564944223a307831386461613261362c22566572223a22312e392e302e313938222c22436f6465223a3078322c22537562436f6465223a3078617d91
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000107047b7b2254797065223a2242544654303030312d3030303132347c307834357c30783835222c2254696d65223a307836336166653131312c224944223a3078342c22564944223a307831386461613261362c22566572223a22312e392e302e313938222c22436f6465223a3078312c22537562436f6465223a3078317d71
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d01010302040000001204617b2254797065223a2242544654303030312d3030303132347c307834377c30783836222c2254696d65223a307836336166653131312c224944223a3078342c224f7574223a3078312c2254494d45444946464552454e4345223a3078383139627d13
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000c0404587b2254797065223a2242544654303030312d3030303132347c307831627c30783761222c2254696d65223a307836336166653132632c224944223a3078352c22436f6465223a3078312c22537562436f6465223a3078307d77
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000120047b7b2254797065223a2242544654303030312d3030303132347c307831657c30783762222c2254696d65223a307836336166653132632c224944223a3078352c22564944223a307831353562646439662c22566572223a22312e392e302e313938222c22436f6465223a3078332c22537562436f6465223a3078317d7b
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000107047b7b2254797065223a2242544654303030312d3030303132347c307834657c30783837222c2254696d65223a307836336166653131322c224944223a3078342c22564944223a307831386461613261362c22566572223a22312e392e302e313938222c22436f6465223a3078312c22537562436f6465223a3078327d1a
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000120047b7b2254797065223a2242544654303030312d3030303132347c307831667c30783763222c2254696d65223a307836336166653132632c224944223a3078352c22564944223a307831353562646439662c22566572223a22312e392e302e313938222c22436f6465223a3078312c22537562436f6465223a3078317dfe
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d01010302040000012204587b2254797065223a2242544654303030312d3030303132347c307832307c30783764222c2254696d65223a307836336166653132632c224944223a3078352c22436f6465223a3078372c22537562436f6465223a3078317d8f
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000108047b7b2254797065223a2242544654303030312d3030303132347c307835307c30783838222c2254696d65223a307836336166653131322c224944223a3078342c22564944223a307831386461613261362c22566572223a22312e392e302e313938222c22436f6465223a3078312c22537562436f6465223a3078357d24
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000120047b7b2254797065223a2242544654303030312d3030303132347c307835317c30783839222c2254696d65223a307836336166653132652c224944223a3078342c22564944223a307831386461613261362c22566572223a22312e392e302e313938222c22436f6465223a3078342c22537562436f6465223a3078307d5e
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d01010302040000012204587b2254797065223a2242544654303030312d3030303132347c307835327c30783861222c2254696d65223a307836336166653132652c224944223a3078342c22436f6465223a3078362c22537562436f6465223a3078317d75
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000120047b7b2254797065223a2242544654303030312d3030303132347c307835337c30783862222c2254696d65223a307836336166653132652c224944223a3078342c22564944223a307831386461613261362c22566572223a22312e392e302e313938222c22436f6465223a3078342c22537562436f6465223a3078307d86
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d01010302040000012204587b2254797065223a2242544654303030312d3030303132347c307832377c30783765222c2254696d65223a307836336166653132632c224944223a3078352c22436f6465223a3078352c22537562436f6465223a3078307dc9
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000c0404587b2254797065223a2242544654303030312d3030303132347c307835377c30783863222c2254696d65223a307836336166653132652c224944223a3078342c22436f6465223a3078312c22537562436f6465223a3078307d37
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000a0404587b2254797065223a2242544654303030312d3030303132347c307832627c30783766222c2254696d65223a307836336166653132642c224944223a3078352c22436f6465223a3078302c22537562436f6465223a3078307df2
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d01010302040000012204587b2254797065223a2242544654303030312d3030303132347c307835617c30783864222c2254696d65223a307836336166653132652c224944223a3078342c22436f6465223a3078352c22537562436f6465223a3078307dd1
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000a0404587b2254797065223a2242544654303030312d3030303132347c307832647c30783830222c2254696d65223a307836336166653132642c224944223a3078352c22436f6465223a3078302c22537562436f6465223a3078307dd3
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000120047b7b2254797065223a2242544654303030312d3030303132347c307835647c30783865222c2254696d65223a307836336166653132662c224944223a3078342c22564944223a307831386461613261362c22566572223a22312e392e302e313938222c22436f6465223a3078332c22537562436f6465223a3078317d81
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000124047b7b2254797065223a2242544654303030312d3030303132347c307832657c30783831222c2254696d65223a307836336166653132642c224944223a3078352c22564944223a307831353562646439662c22566572223a22312e392e302e313938222c22436f6465223a3078322c22537562436f6465223a3078377ddc
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000120047b7b2254797065223a2242544654303030312d3030303132347c307835657c30783866222c2254696d65223a307836336166653132662c224944223a3078342c22564944223a307831386461613261362c22566572223a22312e392e302e313938222c22436f6465223a3078312c22537562436f6465223a3078317ddf
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d01010302040000012204587b2254797065223a2242544654303030312d3030303132347c307835667c30783930222c2254696d65223a307836336166653132662c224944223a3078342c22436f6465223a3078372c22537562436f6465223a3078317db3
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000124047b7b2254797065223a2242544654303030312d3030303132347c307833307c30783832222c2254696d65223a307836336166653132642c224944223a3078352c22564944223a307831353562646439662c22566572223a22312e392e302e313938222c22436f6465223a3078312c22537562436f6465223a3078667d66
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000123047b7b2254797065223a2242544654303030312d3030303132347c307833317c30783833222c2254696d65223a307836336166653132642c224944223a3078352c22564944223a307831353562646439662c22566572223a22312e392e302e313938222c22436f6465223a3078332c22537562436f6465223a3078307db6
DEBUG:SPPDevice:Thread-6 (_thread)  recv 0a0d010103020400000123047b7b2254797065223a2242544654303030312d3030303132347c307836357c30783931222c2254696d65223a307836336166653133622c224944223a3078342c22564944223a307831386461613261362c22566572223a22312e392e302e313938222c22436f6465223a3078342c22537562436f6465223a3078307d05
DEBUG:SPPDevice:Thread-6 (_thread)  recv 2b03080100a7
DEBUG:SPPDevice:Thread-6 (_thread)  recv 2b2a0102000015
DEBUG:SPPDevice:Thread-6 (_thread)  recv 2b03080101b7
DEBUG:SPPDevice:Thread-6 (_thread)  recv 2b03080101b7
DEBUG:SPPDevice:Thread-6 (_thread)  recv 2b2a0102000015
DEBUG:SPPDevice:Thread-6 (_thread)  recv 2b2a0102000015
INFO:SPPDevice:Thread-6 (_thread)  Leaving recv...
INFO:FreebudsManager:Thread-5 (_thread)  State changed to 1
INFO:Applet:Thread-3 (_thread)  Change icon: state_offline
DEBUG:Applet:Thread-3 (_thread)  Menu updated, hash=b1508a13bf4d03cbe2560e893a8c3285ef368b2b
INFO:AutoConfig:Thread-3 (_thread)  Attempt to change device automatically
INFO:SPPDevice:Thread-7 (_thread)  leaving send thread...

*** First pair was disconnected ***

INFO:AutoConfig:Thread-3 (_thread)  Attempt to change device automatically

*** Second pair was connected ***

INFO:AutoConfig:Thread-3 (_thread)  Attempt to change device automatically
INFO:AutoConfig:Thread-3 (_thread)  Use HUAWEI FreeBuds 4i BA:AD:CO:DE:22:22
INFO:FreebudsManager:Thread-3 (_thread)  State changed to 0
INFO:FreebudsManager:Thread-5 (_thread)  leaving manager thread...
DEBUG:FreebudsManager:Thread-3 (_thread)  Running mainloop via safe wrapper
DEBUG:FreebudsManager:Thread-9 (_thread)  Started
DEBUG:root:Thread-3 (_thread)  config file updated
INFO:Applet:Thread-3 (_thread)  Change icon: state_no_dev
DEBUG:Applet:Thread-3 (_thread)  Menu updated, hash=8629732df04f6498e397e174d3d3e7abaea67a2b
INFO:AutoConfig:Thread-3 (_thread)  Attempt to change device automatically
INFO:FreebudsManager:Thread-9 (_thread)  Trying to create SPP device and connect...
INFO:FreebudsManager:Thread-9 (_thread)  State changed to 3
INFO:AutoConfig:Thread-3 (_thread)  Use HUAWEI FreeBuds 4i BA:AD:CO:DE:22:22
INFO:FreebudsManager:Thread-3 (_thread)  State changed to 0
INFO:SPPDevice:Thread-9 (_thread)  Found serial port BA:AD:CO:DE:22:22:16 from UUID
DEBUG:SPPDevice:Thread-9 (_thread)  Starting via safe wrapper
INFO:SPPDevice:Thread-10 (_thread)  starting recv...
DEBUG:SPPDevice:Thread-9 (_thread)  Starting via safe wrapper
INFO:SPPDevice:Thread-11 (_thread)  starting send thread...
DEBUG:SPPDevice:Thread-11 (_thread)  send 5a001f0001070100020003000400050006000700080009000a000b000c000f00190002d9
DEBUG:SPPDevice:Thread-10 (_thread)  recv 010702020124030b484c314f54454d325f56420709312e392e302e3139380910553355424232313432383130303935340a0f42544654303030312d3030303132340f0842544654303030311810424239444b44323134444138353039301901033b
DEBUG:SPPDevice:Thread-11 (_thread)  send 5a0007000c0201000300d9d2
DEBUG:SPPDevice:Thread-10 (_thread)  recv 0c02030b7a682d434e2c656e2d4742040101ee
DEBUG:SPPDevice:Thread-11 (_thread)  send 5a0009000108010002000300fbb9
DEBUG:SPPDevice:Thread-10 (_thread)  recv 010801015a02035f5a64030300000017
DEBUG:SPPDevice:Thread-11 (_thread)  send 5a0005002b2a0100427e
DEBUG:SPPDevice:Thread-10 (_thread)  recv 2b2a0102000015
DEBUG:SPPDevice:Thread-11 (_thread)  send 5a0005002b110100772a
DEBUG:SPPDevice:Thread-10 (_thread)  recv 2b11010100cf
DEBUG:SPPDevice:Thread-11 (_thread)  send 5a000500012d0101882a
DEBUG:SPPDevice:Thread-10 (_thread)  recv 012d010101f2
DEBUG:SPPDevice:Thread-11 (_thread)  send 5a000700012001000200e897
DEBUG:SPPDevice:Thread-10 (_thread)  recv 0120010107020101030501020700ffba
DEBUG:SPPDevice:Thread-11 (_thread)  send 5a0007002b170100020030a7
DEBUG:SPPDevice:Thread-10 (_thread)  recv 2b1701010a02010a030b000102030405060708090aa4
DEBUG:SPPDevice:Thread-11 (_thread)  send 5a0007002b1901000200ff0f
DEBUG:SPPDevice:Thread-10 (_thread)  recv 2b19010101020101030a0102030405060708090a5a
INFO:FreebudsManager:Thread-9 (_thread)  State changed to 4
DEBUG:SPPDevice:Thread-10 (_thread)  recv 012701015a02035f5a64030300000101
DEBUG:SPPDevice:Thread-10 (_thread)  recv 012701015a02035f5a64030300000101
INFO:FreebudsManager:Thread-9 (_thread)  leaving manager thread...
DEBUG:SPPDevice:Thread-9 (_thread)  Closing device...
INFO:SPPDevice:Thread-10 (_thread)  Leaving recv...
DEBUG:FreebudsManager:Thread-3 (_thread)  Running mainloop via safe wrapper
DEBUG:FreebudsManager:Thread-12 (_thread)  Started
ERROR:RunSafe:Thread-3 (_thread)  Action Applet failed.
Traceback (most recent call last):
  File "/opt/openfreebuds/openfreebuds_applet/utils.py", line 96, in _internal
    func(*args, **kwargs)
  File "/opt/openfreebuds/openfreebuds_applet/applet.py", line 155, in _ui_update_loop
    self.update_icon()
  File "/opt/openfreebuds/openfreebuds_applet/applet.py", line 93, in update_icon
    battery_left = dev.find_property("battery", "left", 0)
AttributeError: 'NoneType' object has no attribute 'find_property'
INFO:FreebudsManager:Thread-12 (_thread)  Trying to create SPP device and connect...
INFO:FreebudsManager:Thread-12 (_thread)  State changed to 3
INFO:SPPDevice:Thread-12 (_thread)  Found serial port BA:AD:CO:DE:22:22:16 from UUID
DEBUG:SPPDevice:Thread-12 (_thread)  Starting via safe wrapper
INFO:SPPDevice:Thread-13 (_thread)  starting recv...
DEBUG:SPPDevice:Thread-12 (_thread)  Starting via safe wrapper
INFO:SPPDevice:Thread-14 (_thread)  starting send thread...
DEBUG:SPPDevice:Thread-14 (_thread)  send 5a001f0001070100020003000400050006000700080009000a000b000c000f00190002d9
DEBUG:SPPDevice:Thread-13 (_thread)  recv 010702020124030b484c314f54454d325f56420709312e392e302e3139380910553355424232313432383130303935340a0f42544654303030312d3030303132340f0842544654303030311810424239444b44323134444138353039301901033b
DEBUG:SPPDevice:Thread-14 (_thread)  send 5a0007000c0201000300d9d2
DEBUG:SPPDevice:Thread-13 (_thread)  recv 0c02030b7a682d434e2c656e2d4742040101ee
DEBUG:SPPDevice:Thread-14 (_thread)  send 5a0009000108010002000300fbb9
DEBUG:SPPDevice:Thread-13 (_thread)  recv 010801015a02035f5a64030300000107
DEBUG:SPPDevice:Thread-14 (_thread)  send 5a0005002b2a0100427e
DEBUG:SPPDevice:Thread-13 (_thread)  recv 2b2a0102000015
DEBUG:SPPDevice:Thread-14 (_thread)  send 5a0005002b110100772a
DEBUG:SPPDevice:Thread-13 (_thread)  recv 2b11010100cf
DEBUG:SPPDevice:Thread-14 (_thread)  send 5a000500012d0101882a
DEBUG:SPPDevice:Thread-13 (_thread)  recv 012d010101f2
DEBUG:SPPDevice:Thread-14 (_thread)  send 5a000700012001000200e897
DEBUG:SPPDevice:Thread-13 (_thread)  recv 0120010107020101030501020700ffba
DEBUG:SPPDevice:Thread-14 (_thread)  send 5a0007002b170100020030a7
DEBUG:SPPDevice:Thread-13 (_thread)  recv 2b1701010a02010a030b000102030405060708090aa4
DEBUG:SPPDevice:Thread-14 (_thread)  send 5a0007002b1901000200ff0f
DEBUG:SPPDevice:Thread-13 (_thread)  recv 2b19010101020101030a0102030405060708090a5a
INFO:FreebudsManager:Thread-12 (_thread)  State changed to 4
INFO:SPPDevice:Thread-11 (_thread)  leaving send thread...
```

**Comment by melianmiko** [comment]
Can you please check, is error gone after that commit?

**Comment by melianmiko** [comment]
Fine, I'll make a release with this fixes in a few days.
